//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspprj
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbler
    {
        public int rno { get; set; }
        public string name { get; set; }
        public Nullable<decimal> m1 { get; set; }
        public Nullable<decimal> m2 { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> average { get; set; }
        public string result { get; set; }
    }
}
